# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f15d2d5cfec2fc4d31d6c97f4b74b076cfc8953acc9cc2a44c71ce037a79e80f1207a0d1d2a29b78f2f7c3d9b2ad1d10fee35fa247af6b0704c822be124fc6ff

test:
  secret_key_base: 4bd298849b397272b97b46d88fc645e0a20a98e57002ad1618e8e5d1f7fb6a255d484b10b51a1964154aa395be1d13dfeb378c0a6bda159d0acff14cdb1b41ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
